sudo: required
language: generic 
services: 
  - docker 

before_install:
  - docker build -t catarinagomes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true catarinagomes/docker-react npm run test

deploy:
  provider: elasticbeanstalk #tell Travis CI who's the host, it could be AWS or Digital Ocean or etc
  region: "us-east-2" #this region depends on the link http://dockerreact-env.eba-mttauntc.us-east-2.elasticbeanstalk.com/
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-667445575805"
  bucket_path: "docker-react" #the default path is equal to the app name
  on: 
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
