sudo: required
language: generic 
services: 
  - docker 

before_install:
  - docker build -t catarinagomes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true catarinagomes/docker-react npm run test

  